### DISCUSSION TITLE
Where store root.key in docker-compose/Get root.key same root.crt

### DISCUSSION THREAD

**Discussion by patsevanton** [smallstep/certificates#1737] [Q&A] [answered]
Hello! Thanks for smallstep!
i run docker-compose.yaml:
```
version: "3.8"

services:
  step-ca:
    image: smallstep/step-ca:0.25.2
    container_name: step-ca
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DOCKER_STEPCA_INIT_NAME="Root CA My Corp"
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)
      - DOCKER_STEPCA_INIT_PASSWORD_FILE=/password.txt
    volumes:
      - step-ca:/home/step
      - ${PWD}/password.txt:/password.txt
volumes:
  step-ca:
```

Get its root certificate from the Smallstep CA:
```shell
step ca root root_ca.crt
```

Creating a signature key and a certificate request. Enter the password specified in DOCKER_STEPCA_INIT_PASSWORD_FILE
```shell
step certificate create "Intermediate CA Name" intermediate.csr intermediate_ca_key --csr
```

Signing the request for an intermediate certificate.
```shell
step certificate sign --profile intermediate-ca intermediate.csr root_ca.crt root.key
```

Where store root.key in docker-compose ?
May i get root.key same root_ca.crt ?
May i create root.key before and set in docker-compose ?
