### DISCUSSION TITLE
Do I need smallstep-ca or just smallstep-cli

### DISCUSSION THREAD

**Discussion by callahan22** [smallstep/certificates#1787] [General]
I've finally decided to do something about the huge number of internal sites and devices that use self signed certs. I'm looking for a simple CA that I can pass CSRs to, get them signed, grab the cert and install. I've used a combo of OpenSSL for generating CSRs and Windows CA Server to sign them for years through work so just looking for a simpler setup for home.
I assumed I needed smallstep-ca which I plan to run via docker so thats set up and running as per the below. * I realise we're not supposed to be setting passwords as env variables. I'm jut trying to get it working for now.

```
  smallstep-ca:
    container_name: smallstep-ca
    image: smallstep/step-ca:latest
    restart: unless-stopped
    volumes:
      - ./smallstep-ca:/home/step
    ports:
      - "9000:9000"
    environment:
      - "DOCKER_STEPCA_INIT_NAME=Smallstep"
      - "DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)"
      - "DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true"
      - "DOCKER_STEPCA_INIT_PROVISIONER_NAME=admin"
      - "DOCKER_STEPCA_INIT_PASSWORD=a5h19YG4PdY_2uq!7-k"
```

Then I've read here that smallstep-ca is not required to run a CA: https://smallstep.com/docs/step-cli/#introduction-to-step

**Examples that don't require step-ca**
Create and work with X.509 certificates](https://smallstep.com/docs/step-cli/basic-crypto-operations/#create-and-work-with-x509-certificates)

https://smallstep.com/docs/step-cli/basic-crypto-operations/#create-a-certificate-authority
You can use it to create certificate signing requests (CSRs), sign CSRs, create self-signed certificates (e.g., a root certificate authority), create leaf or intermediate CA certificates, validate and inspect certificates, renew certificates, generate certificate bundles, and to key-wrap private keys.

So the first question I have is which should I be running? Experience tells me that I will definitely need a CA as that's how I've worked for years.

Second question is, assuming I'm going the CA Server route via docker, once i have it running, how do I submit a CSR for signing? I'm finding mixed resources and none of them seem to offer a simple set of steps to submit a CSR and get the resulting certificate.

Thanks for any advice you can offer!
