### DISCUSSION TITLE
Step ca provisioner update: error applying certificate template

### DISCUSSION THREAD

**Discussion by Rajstopy** [smallstep/certificates#2011] [Q&A] [answered]
Hi there!

Going on my step-ca discovery, it looks like a kind of one step forward, two steps back story…

I’m now stuck in trying to apply a template to my JWK provisioner. I did it successfully the first time issuing the following command, from within the container:

`02f7d02123a1:/home/step# step ca provisioner update JWK --create --x509-template /home/step/templates/x509/leaf.tpl`

The template was applied:

```sh
02f7d02123a1:/home/step# step ca provisioner list
[
   {
      "type": "JWK",
      "name": "Admin JWK",
      "key": {
         "use": "sig",
         "kty": "EC",
         "kid": "uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg",
         "crv": "P-256",
         "alg": "ES256",
         "x": "Vq38mf_YBbTrAuXRbmIc8tLcl3dBB2zy7F9npppr0kI",
         "y": "hwFYB7iX_Dy4Dhz140QR7GbjJ2GWM8CimBpguJxJUAY"
      },
      "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoiSzRJRVJiNzVnX3dKYUVYRmpxV3BMUSJ9.XmHVcJzhGQ2SeK3Zjhx1atRdmBay9erwBVUrsfXmJhaCDg2DVjgU6g.0JPSwq_6qb_Aj-9N.UpIzNp6Ac75hL1TPsj4HgiAN1R9wOSXGD6c796dWpe1cgr1peUD1uUG6ReGxlRTqJf744cqlGWc4JJ5AiS-sOLKyq6yadY3JsrmPN_BVqUsprJx85wZE3vs8HPMOvp_pRZyw1tDmVj45EpzLY8zrfh7IUTaYFRZBKTJIO4zrSQFtLjXc7Jy9DoQGcgg4Cv4ixrIUVqDx3ic0-lW9SJ8Ld511U-gVPFtnO7PRUACK25HiVhWEH-7EN1P-EUV2WAxTr0PMhU6iY_DGAYfvLyODcllzhZQPvBZEM6FlW4bDTzwaPcZHKrEJ_nmqVHrBTEDCqjyLxr0fL4Ruus0pkfc.Q5Nl9kjaVfIPmxBqOhWREg",
      "claims": {
         "defaultTLSCertDuration": "24h0m0s",
         "enableSSHCA": false,
         "disableRenewal": false,
         "allowRenewalAfterExpiry": false,
         "disableSmallstepExtensions": false
      },
      "options": {
         "x509": {
            "template": "{\n        \"subject\": {\n                \"commonName\": {{ toJson .Subject.CommonName }},\n                \"country\": \"FR\",\n\t\t\"state\": \"XXX\",\n                \"locality\": \ »XXX\ »,\n                \"organization\": \"Home\",\n\t\t\"emailAddress\": admin@mytest.fr\n        },\n{{- if .SANs }}\n        \"sans\": {{ toJson .SANs }},\n{{- end }}\n{{- if typeIs \"*rsa.PublicKey\" .Insecure.CR.PublicKey }}\n        \"keyUsage\": [\"keyEncipherment\", \"digitalSignature\"],\n{{- else }}\n        \"keyUsage\": [\"digitalSignature\"],\n{{- end }}\n        \"extKeyUsage\": [\"serverAuth\", \"clientAuth\"]\n}\n"
         },
         "ssh": {}
      }
   }
]
```
But now, each time I try to apply another template or reset the setting, I get the following error:

```sh
02f7d02123a1:/home/step# step ca provisioner update "Admin JWK" --x509-template ""
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): step
✔ Provisioner: Admin JWK (JWK) [kid: uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg]
Please enter the password to decrypt the provisioner key: 
error applying certificate template
Re-run with STEPDEBUG=1 for more info.

02f7d02123a1:/home/step# step ca provisioner update JWK --x509-template ""
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): step
✔ Provisioner: Admin JWK (JWK) [kid: uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg]
Please enter the password to decrypt the provisioner key: 
error applying certificate template
Re-run with STEPDEBUG=1 for more info.


02f7d02123a1:/home/step# step ca provisioner update JWK --x509-template ""
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): step
✔ Provisioner: Admin JWK (JWK) [kid: uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg]
Please enter the password to decrypt the provisioner key: 
error applying certificate template
Re-run with STEPDEBUG=1 for more info.

02f7d02123a1:/home/step# step ca provisioner update JWK --create --x509-template /home/step/templates/x509/leaf.tpl
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): step
✔ Provisioner: Admin JWK (JWK) [kid: uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg]
Please enter the password to decrypt the provisioner key: 
error applying certificate template
Re-run with STEPDEBUG=1 for more info
```
Here is the log output:
```log
time="2024-09-24T15:50:43+02:00" level=error duration=2.954217ms duration-ns=2954217 error="error applying certificate template: invalid character 'a' looking for beginning of value at offset 216" fields.time="2024-09-24T15:50:43+02:00" method=POST name=ca ott=eyJhbGciOiJFUzI1NiIsImtpZCI6InVEUzR4WXNQSDFkSkM1eHp6UEtsaXN4bnk1TGxpUW9OdnNQbTBKZjVfWmciLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL2lyY3NvdjAyOjkwMDAvMS4wL3NpZ24iLCJleHAiOjE3MjcxODYxNDMsImlhdCI6MTcyNzE4NTg0MywiaXNzIjoiQWRtaW4gSldLIiwianRpIjoiMTI0ZTQ1OWZhZGFlN2UzMTFlMWQxYjU1ZmUzNTJjNTViMGIwZDViNjMxMDU4YWFlYTIwNTE2ZDlmZDEzNDA5YSIsIm5iZiI6MTcyNzE4NTg0Mywic2FucyI6WyJzdGVwIl0sInNoYSI6ImZjNTc4MTRmODhjNWIzYTQxZjBmODNkMmUzYzRmYjZkNjY1NmQyZTMwYTEwNWE2Nzc4YWI5OTA4M2JlZjBlOTgiLCJzdWIiOiJzdGVwIn0.m2t2UG0_kTGpuHQk-56XRnurpj5dak0wC6KHoMAjlANHdQXMtq3E4-KA-2rGzH5J8Rh14mfzRWWMZsSbjLivtA path=/sign protocol=HTTP/2.0 referer= remote-address=127.0.0.1 request-id=47db223b-5cb9-4028-8176-5c0250800150 size=63 status=500 user-agent="Smallstep CLI/0.27.4 (linux/amd64)" user-id=
```
What is weird, is that I get the same kind of error when trying to list the admin accounts… 

```sh
02f7d02123a1:/home/step# step ca admin list
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): step
✔ Provisioner: Admin JWK (JWK) [kid: uDS4xYsPH1dJC5xzzPKlisxny5LliQoNvsPm0Jf5_Zg]
Please enter the password to decrypt the provisioner key: 
error applying certificate template
Re-run with STEPDEBUG=1 for more info.
```

Is there something I didn’t understand?

As a reminder, here is my docker-compose:
```yaml
version: '3.7'
x-step-ca: &step-ca_environment
  DOCKER_STEPCA_INIT_NAME: 'Test-CA'
  DOCKER_STEPCA_INIT_DNS_NAMES: ‘xxx, xxx’
  DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: true
  DOCKER_STEPCA_INIT_SSH: true
  DOCKER_STEPCA_INIT_PROVISIONER_NAME: 'ca-test-admin'
  TZ: 'Europe/Paris'


x-step-db: &step-db_environment
  MYSQL_DATABASE: step-ca
  MYSQL_USER: step-ca-user
  MYSQL_PASSWORD: ‘xxx’
  MYSQL_ROOT_PASSWORD: ‘xxx’
  TZ: 'Europe/Paris'

services:
  step-ca-server:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped
    user: root
    environment: *step-ca_environment
    volumes:
      - '/mnt/docker/step-ca:/home/step'
    networks:
      - step-ca-network
    ports:
      - '9000:9000'
    depends_on:
      - db

  db:
    image: mysql:9.0
    container_name: step-db
    hostname: step-db
    restart: unless-stopped
    volumes:
      - '/mnt/docker/step-ca/mysql:/var/lib/mysql'
    environment: *step-db_environment
    mem_limit: 512M   # Limit the container to 512MB of memory
    cpus: "1.0"       # Limit the container to 1 CPU core
    networks:
      - step-ca-network

networks:
  step-ca-network:
    driver: bridge
```

I would need any insight if possible…
