### DISCUSSION TITLE
How to get an HTTP-01 tls.key

### DISCUSSION THREAD

**Discussion by BenB196** [smallstep/certificates#923] [Q&A] [answered]
Hi All, I'm not sure if I'm asking in the correct spot, but figured I'd see if anyone knows the answer.

I have step-ca setup via [helm](https://github.com/smallstep/helm-charts/tree/master/step-certificates) and I'm trying to get it to work with [cert-manager](https://cert-manager.io/) http-01 challenge. The one thing I've been update to find out reading either step-ca or cert-manager docs, is how to I generate a tls.key to be used with the http-01 challenge.

My step ca provisioners looks something like:

```yaml
provisioners:
- claims: {}
forceCN: false
name: acme
type: ACME
- encryptedKey: >- <snipped>
key:
  alg: ES256
  crv: P-256
  kid: <snipped>
  kty: EC
  use: sig
  x: <snipped>
  'y': <snipped>
name: cert-manager
type: JWK
```

My issue is cert-manager requires a `privateKeySecretRef` with a `tls.key` value, but neither project really explains how to get this:

```yaml
apiVersion: cert-manager.io/v1kind: Issuer
metadata:
  name: dev-acme-server
  namespace: cert-manager-development
spec:
  acme:
    preferredChain: ""
    privateKeySecretRef:
      name: some-tls-key-i-dont-know-how-to-get #< ---- This should contain a tls.key value, but how do you get it?
    server: https://step-ca.internal.domain.com:9001/acme/acme/directory
    solvers:
    - http01:
        ingress:
          name: traefik
```
