### ISSUE TITLE
Make it possible to hide Database password in "dataSource" configuration setting

### ISSUE THREAD

**Issue by kudiyarov** [smallstep/certificates#1256]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For now the only way to specify PostgreSQL/MySQL DSN is using ".db.dataSource" field in "ca.json" configuration file. Sometimes It is not safe (not convinient) because DB password (or whole URL) should be specified right in the k8s ConfigMap.

For instance, I use postgresql-operator that generates random password right to the k8s Secret. Then I need to re-use it somehow...

Possible solutions could be:
1) Allow to specify environment variables in ca.json config. 
`.db.dataSource: "postgresql://step_ca:${PG_PASSWORD}@step-ca-pg:5432"`
Then I would be able to specify env variable in step-ca's StatefulSet/Deployment.
2) Make a special field ".db.dataSourceFile" where I can specify the path to the file that contains DB DSN, which I can pre-build separately in step-ca StatefulSet/Deployment as:
`.db.dataSourceFile: "/run/secrets/db/postgresql-dsn.txt"`
This approach may require some initContainer that builds string with DB's DSN and writes it to that "dataSourceFile" on EmptyDir mounted directory. Looks a bit ugly:)
3) Allow to specify all DB settings as environment variables. Something like this:
```
- name: DATABASE_TYPE
  value: {{ .Values.database.type }}
- name: DATABASE_HOST
  value: {{ .Values.database.host }}
- name: DATABASE_PORT
  value: {{ .Values.database.port }}
- name: DATABASE_NAME
  value: {{ .Values.database.name }}
- name: DATABASE_USER
  value: {{ .Values.database.user }}
- name: DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ .Values.database.password.secret.name }}
      key: {{ .Values.database.password.secret.key }}
```

## Why is this needed?
1) Store sensitive data in the k8s Secret.
2) In case when somebody uses postgresql-operator, this allows to build deployment pipeline without manual steps.

**Comment by benlongo** [comment]
I'm not sure if this solves your problem, but I believe `pgx` is being used under the hood which (I think) supports the standard postgres env vars (https://www.postgresql.org/docs/current/libpq-envars.html) which include `PGPPASSWORD` and `PGPASSFILE`. I have not tested this myself

**Comment by kudiyarov** [comment]
Yeah, this solves my case. Thank You @benlongo! Didn't know about this `pgx` feature.
I was able to deploy `step-ca` with the following helm values:
```
...
inject:
  config:
    files:
      ca.json:
        db:
          type: postgresql
          dataSource: postgresql://step-ca-pg:5432/step_ca
...
ca:
  env:
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: username
          name: step-ca.step-ca-pg.creds.postgresql.acid.zalan.do
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: step-ca.step-ca-pg.creds.postgresql.acid.zalan.do
...
```

I guess clarifying this in the docs will be great.
