### ISSUE TITLE
[Docker] listen tcp 127.0.0.1:443: bind: permission denied

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#170]
### Subject of the issue
When `step ca` server should bind to the default ACME port 443, it fails in docker:
````
listen tcp 127.0.0.1:443: bind: permission denied
````

### Your environment
* OS: WSL (Bash on Windows)
* Version: Windows 10 Pro x64

### Steps to reproduce
`docker-compose.yml`:
```yml
version: '3.7'

services:
  step-ca:
    image: smallstep/step-ca:0.14.0-rc.2
    # currently needed for step-ca
    tty: true
    command: "step-ca /step/config/ca.json --password-file=/step/secrets/password"
    volumes:
      - "./step:/step"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`ca.localhost`)
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.routers.traefik.service: api@internal
    networks:
      - "web"

networks:
  web:
    external: true
````

### Expected behaviour
The `step ca` container should go up and listen on port 443.

### Actual behaviour
The `step ca` container fails to go up, and fails with error:
````
listen tcp 127.0.0.1:443: bind: permission denied
````

### Additional context
This seems to be an usual issue with `go` applications, I found similar issues with `caddy`.
