### ISSUE TITLE
[Bug]: ERROR: for step-ca  'ContainerConfig' (docker-compose)

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [smallstep/certificates#1857]
### Steps to Reproduce

Run this in **docker-compose**
```
  step-ca:
    image: smallstep/step-ca:latest
    environment:
      - DOCKER_STEPCA_INIT_NAME="Acme Corp"
      - DOCKER_STEPCA_INIT_DNS_NAMES="step-ca.docker"
      - DOCKER_STEPCA_INIT_PASSWORD=mysecretpassword
```

### Your Environment

* OS -
Debian GNU/Linux 12 (bookworm) aarch64 

* `step-ca` Version -
latest (supplied in docker)

### Expected Behavior

Starting spiderunderurbed_step-ca...

### Actual Behavior

https://pastebin.com/fUinrfPa

### Additional Context

I dont know what other logs or information to apply, if any is asked, i will happily give

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
