### ISSUE TITLE
order IDs changed since last read

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#189]
### Subject of the issue
smalstep CA server responds with
````
order IDs changed since last read
````

### Your environment
* OS: WSL (Bash on Windows), (Ubuntu)
* Version: WSL 1 (stable), (Windows 10 x64 Pro)

### Steps to reproduce
Up a smallstep CA container and a traefik container that uses the CA container as certresolver.

### Expected behaviour
No such errors, certs are signed correctly.

### Actual behaviour
smallstep CA serverside error `order IDs changed since last read` and the site cert is not signed for traefik.

### Additional context
badger2 database used, persisted in mounted docker volume on host.

**Comment by dopey** [comment]
I just tried running the badger2 release on OSX and I'm able to request and receive ACME certificates from the CA w/out issue from the database.

What client are you using to make the ACME requests against the CA? I just tried with the `step` acme client.

I'll see if I can get someone on the team to test with WSL.

**Comment by strarsis** [comment]
@dopey: The ACME client is Traefik using smallstep CA as certresolver.

**Comment by strarsis** [comment]
Currently I have to wipe the step-ca database datadir and restart with an empty database to fix this error.
Using docker image `smallstep/step-ca:0.14.0-rc.14`.

**Comment by dopey** [comment]
I assume you just have to wipe it once and not each time you restart `step-ca`, right?

Good news is that a fix has been pushed to badger allowing the use of Badger2 alongside Badger1 which means we can integrate Badger2 into the general release. It's on my shortlist of things to do in the next few weeks.

**Comment by sebastien-baillet** [comment]
A little off-topic but I can't make may Traefik works with step-ca, I have the following error in Traefik logs:

```
time="2020-04-10T14:05:20Z" level=error msg="Unable to obtain ACME certificate for domains \"whoami.mycompany.com\": cannot get ACME client get directory at 'https://ca.mycompany.com/acme/acme/directory': Get \"https://ca.mycompany.com/acme/acme/directory\": x509: certificate signed by unknown authority" providerName=myacme.acme routerName=whoami@docker rule="Host(`whoami.mycompany.com`)"
```

In my case, step-ca is a sub-CA.
I tried to set rootCAs without any success:

```
serversTransport:
  rootCAs:
    - /etc/traefik/certs/root_ca.crt
```

How did you do to Traefik trusts your root CA ?

**Comment by strarsis** [comment]
@sebastien-baillet: Are you using Traefik v2?
I had to define step-ca as a cert resolver and then make all docker containers use it as tls cert resolve

**Comment by sebastien-baillet** [comment]
I'm using Traefik v2.
Extract from my traefik.yaml:

```
certificatesResolvers:
  myacme:
    acme:
      email: me@mycompany.com
      storage: /etc/traefik/acme/acme.json
      caServer: https://ca.mycompany.com/acme/acme/directory
      httpChallenge:
        entrypoint: web
```

Extract from my docker-compose.yml:

```
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.mycompany.com`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myacme"
```

Any idea?
