### ISSUE TITLE
[Bug]: Error on Windows CRYPT_E_NO_REVOCATION_CHECK root_ca not in cert store

### ISSUE THREAD

**Issue by muuvmuuv** [smallstep/certificates#2150]
### Steps to Reproduce

I ran the bootstrap command with `--install` on a Windows 10 and 11 but cannot find the trusted certificate in the trusted computer store nor does a curl command respond without an error. This results in Apache not being able to call /directory to our step-ca server. The command itself reports the installation succeeded. 

### Your Environment

Windows 10 Pro 22H2
Windows 11 Pro 24H2
Smallstep CLI/0.28.2 (windows/amd64)
Release Date: 2024-11-20T19:14:16Z

### Expected Behavior

.

### Actual Behavior

```
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - Die Sperrfunktion konnte keine Sperrprüfung für das Zertifikat durchführen.
```

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Have you checked the system certificate store as well as the user certificate store? 

I assume the error is shown when a curl request is made towards `https://your-step-ca`, not during installation?

**Comment by muuvmuuv** [comment]
Found it at the user certificate store, the computer cert store is empty. I don't know what a system cert store is.

Yeah, the curl fails, not the installation itself. It works on our Debian VM's.

How do I tell curl to use the cert store? I tried the bootstrap with and without admin permissions. No difference. Also curl with `--native-ca`.

We don't have a CRL set up, we only use step-ca internally for our dev-nodes. Is that required? I thought it's just for security for active revocation if the intermediate gets compromised.

**Comment by muuvmuuv** [comment]
Adding the root ca to both trusted stores also does not work, even after restart, with and without admin permssions.

**Comment by hslatman** [comment]
It sounds like the root certificate was installed correctly, so that part is down.

The `CRYPT_E_NO_REVOCATION_CHECK` error is a different issue. Windows is looking for a CRL endpoint, but if you have not configured that to be part of your certificate, it'll fail. You can run the `curl` command with `--ssl-no-revoke` to disable the CRL check, and then it should succeed. 

Then onto the Apache server: is that also running on Windows, and under the same user?

**Comment by muuvmuuv** [comment]
Hm, OK, seems Apache has a similar option with `SSLCARevocationCheck`. I set it to `none` but it still gives me errors.

**Comment by muuvmuuv** [comment]
Yes, the mod_md change will fix it, I will check it once it has a release-build.

Nevertheless, I have also enabled CRL on our step-ca server to give it a try and to just avoid such errors in the future. I have followed the [steps here](https://smallstep.com/docs/step-ca/certificate-authority-server-production/#enable-crl-for-an-intermediate-ca), but still have this error popping. 
I use HTTPS as the protocol in the templates, as I don't want to allow insecure access to that server. Calling curl on that endpoint works and downloads that CRL file, but the Windows machine's curl does get the same error.
The intermediate certs are generated again and I can also call crl inspect successfully on the Windows machine: 

![Image](https://github.com/user-attachments/assets/8b511cda-4ba5-4b17-981c-617f9ecba756)

**Comment by hslatman** [comment]
You may need to follow this instead: https://smallstep.com/docs/step-ca/certificate-authority-server-production/#enable-crl-for-leaf-certificates.

**Comment by muuvmuuv** [comment]
I enabled both ofc, just didn't want to link both ^^ I will test again with unsecure port. The docs btw should also include that the port is mandatory when using http protocol when no proxy is used and the port is something like 9001.

**Comment by hslatman** [comment]
> The docs btw should also include that the port is mandatory when using http protocol when no proxy is used and the port is something like 9001.

Which port? The HTTP port for CRLs? It's not mandatory, as not everyone uses CRLs, and there are also systems that support CRLs via HTTPS.

**Comment by muuvmuuv** [comment]
Ok, I think I found the error cause, when I do a `step certificate inspect https://ca.xxxxx.de` on the client and step-ca server I see that the intermediate certificate in /etc/step-ca/certs has a

```
            X509v3 CRL Distribution Points:
                Full Name:
                  URI:http://ca.xxxx.de:9426/1.0/crl
```

but the windows client has none. So I guess step-ca picks the wrong one somewhere for its server?

**Comment by muuvmuuv** [comment]
Today I have created a new server which I have added a Caddyserver and now I am getting "error decoding template: illegal base64 data at input byte 9". Haven't had that before so I guess that also comes from the crl setup part. I have now followed the docs again 1:1 without luck. Is it correct that template will be inlined into ca.json after `--x509-template`? What is the reason for that, instead of the actual file path in `/templates/`?

**Comment by lumarel** [comment]
I had the same, or a similar issue, and wanted to report how we solved the issue:
- we are centrally serving the CRL file (beside the public keys) on a seperate webserver
- the CRL file is in this case served via a proxy rewrite `http://crl.example.com/issueca.crl` -> `https://issueca.example.int/crl`
- further we use a custom leaf certificate template with `"crlDistributionPoints": ["http://crl.example.com/issueca.crl"], "issuingCertificateURL": "http://crl.example.com/issueca.crt"` set
- finally, `"crl.enabled": true, "crl.idpURL": "http://crl.example.com/issueca.crl"` has to be set

so, only after having matching attributes in the CRL file and in the leaf certificates SChannel started to behave

**Comment by Lukylix** [comment]
> I had the same, or a similar issue, and wanted to report how we solved the issue:
> 
> * we are centrally serving the CRL file (beside the public keys) on a seperate webserver
> * the CRL file is in this case served via a proxy rewrite `http://crl.example.com/issueca.crl` -> `https://issueca.example.int/crl`
> * further we use a custom leaf certificate template with `"crlDistributionPoints": ["http://crl.example.com/issueca.crl"], "issuingCertificateURL": "http://crl.example.com/issueca.crt"` set
> * finally, `"crl.enabled": true, "crl.idpURL": "http://crl.example.com/issueca.crl"` has to be set
> 
> so, only after having matching attributes in the CRL file and in the leaf certificates SChannel started to behave

This is exactly what i did to resolve the issue. I generated a dummy empty CRL file.

---- 
## A guide that could help homelab users :
Create a working directory for CRL generation.

```bash
mkdir -p /opt/containers/step-ca/crl-work
cd /opt/containers/step-ca/crl-work
```

Copy the intermediate CA certificate and key.

```bash
docker compose cp step-ca:/home/step/certs/intermediate_ca.crt .
docker compose cp step-ca:/home/step/secrets/intermediate_ca_key .
```

Create an empty revocation database.

```bash
touch index.txt
echo 1000 > crlnumber
```

Create:

```bash
nano openssl-crl.cnf
```

Content:

```ini
[ ca ]
default_ca = CA_default

[ CA_default ]
database = ./index.txt
crlnumber = ./crlnumber
certificate = ./intermediate_ca.crt
private_key = ./intermediate_ca_key
default_md = sha256
default_crl_days = 30
```

Get the pass:

```bash
 docker compose exec step-ca cat /home/step/secrets/password
```

Create a signed CRL with no revoked certificates.

```bash
openssl ca \
  -config openssl-crl.cnf \
  -gencrl \
  -out intermediate.crl
```

Check that the CRL is valid and empty.

```bash
openssl crl -in intermediate.crl -text -noout
```

Expected:

```
No Revoked Certificates.
```

Choose a distribution endpoint
```bash
nano /opt/containers/step-ca/data/templates/x509.tpl
```

```json
{
  "subject": {{ toJson .Subject }},
  "sans": {{ toJson .SANs }},
  "keyUsage": [
    "digitalSignature",
    "keyEncipherment"
  ],
  "extKeyUsage": [
    "serverAuth",
    "clientAuth"
  ],
  "crlDistributionPoints": [
    "https://trust.cloudy/intermediate.crl"
  ]
}
```
```bash
docker compose exec step-ca step ca provisioner update acme --x509-template=/home/step/templates/x509.tpl
docker compose exec step-ca step ca provisioner list
```

The used associated compose :
```yml
services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: always
    environment:
      - DOCKER_STEPCA_INIT_NAME=CloudyCA
      - DOCKER_STEPCA_INIT_DNS_NAMES=ca.cloudy
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=admin@cloudy
      - DOCKER_STEPCA_INIT_ACME=true

    volumes:
      - /opt/containers/step-ca/data:/home/step
    dns: [10.10.10.10]
    networks:
      traefik:
        aliases: [ca.cloudy]

    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.stepca.rule=HostSNI(`ca.cloudy`)"
      - "traefik.tcp.routers.stepca.entrypoints=websecure-internal"
      - "traefik.tcp.routers.stepca.tls.passthrough=true"
      - "traefik.tcp.services.stepca.loadbalancer.server.port=9000"

  trust-ca-website:
    image: caddy:alpine
    restart: always
    container_name: step-ca-website
    volumes:
      - /opt/containers/step-ca/data/trust-ca.html:/usr/share/caddy/index.html:ro
      - /opt/containers/step-ca/crl-work/intermediate.crl:/usr/share/caddy/intermediate.crl:ro
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trust-ca.rule=Host(`trust.cloudy`)"
      - "traefik.http.routers.trust-ca.entrypoints=websecure-internal"
      - "traefik.http.routers.trust-ca.tls=true"
      - "traefik.http.routers.trust-ca.tls.certresolver=step"
      - "traefik.http.routers.trust-ca.middlewares=cloudy-internal"

networks:
  traefik:
    external: true
```
