### ISSUE TITLE
Health check timeout (container state: unhealthy)

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#463]
### Subject of the issue
The step-ca container health state is shown as `Up (health: starting)`, later it will turn to `Up (unhealthy)`.
But the service runs fine and it also logs that it is listening now, so apparently the health check always fails.

### Your environment
* OS: WSL 2
* Version: 2 (Windows 10 x64)

### Steps to reproduce
`docker-compose.yml`:
```yml
version: '3.7'

services:

  # Smallstep Step CA
  step-ca:
    image: smallstep/step-ca:0.15.6
    restart: always
````
````
> docker-compose up -d
> docker-compose ps
Up (health: starting)
# after some time (about one minute)
> docker-compose ps
Up (unhealthy)
````

### Expected behaviour
As the CA service runs correctly, the health check should pass and the container state should become `Up (healthy)` or similar, but not `Up (unhealthy)`. Also the health check needs too long (`(health: starting)`) for one minute.

### Actual behaviour
Health check needs too long (`Up (health: starting)`) and then fails after about a minute (`Up (unhealthy)`).
