### ISSUE TITLE
Build .dem and .rpm from GoReleaser

### ISSUE THREAD

**Issue by tashian** [smallstep/certificates#768]
Here's a starting point for the nfpm configuration:

```
nfpms:
  - id: packages
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Smallstep Labs, Inc.
    homepage: https://github.com/smallstep/certificates
    maintainer: Smallstep Labs, Inc. <techadmin@smallstep.com>
    description: step-ca is the Smallstep Certificate Authority......
    formats:
      - rpm
    suggests:
      - step-cli
    bindir: /usr/bin
    release: 1
    contents:
      - src: ./systemd/step-ca.service
        dst: /usr/lib/systemd/system/step-ca.service
      - dst: /etc/step-ca
        type: dir
        file_info:
          mode: 0700
```
